/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atsinformatica.midler.ui;

import br.com.atsinformatica.erp.controller.SenhaInstalacaoController;
import br.com.atsinformatica.erp.dao.UsuarioERPDAO;
import br.com.atsinformatica.erp.entity.SenhaInstalacaoERPBean;
import br.com.atsinformatica.erp.entity.UsuarioERPBean;
import br.com.atsinformatica.midler.Main;
import br.com.atsinformatica.midler.entity.SenhaSistema;
import br.com.atsinformatica.midler.facade.UsuarioERPFacade;
import br.com.atsinformatica.utils.Criptogafia;
import br.com.atsinformatica.utils.SenhaSistemaService;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import org.apache.log4j.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kennedimalheiros
 */
public class FrameLogin extends javax.swing.JFrame {
    private UsuarioERPFacade usuarioFacade;

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin() {
        initComponents();
        this.setTitle("Login - Modulo Integrador E-commerce ATS - " + Main.VERSION);
        
        lMensageLogin.setText("");
        tUsuario.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tSenha = new javax.swing.JPasswordField();
        lMensageLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImage( Toolkit.getDefaultToolkit().getImage(System.getProperty("user.dir") + "\\src\\assets\\images\\ecom.png"));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Senha:");

        jButton1.setText("Logar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/ecom.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/logo-w186.png"))); // NOI18N

        tSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSenhaKeyPressed(evt);
            }
        });

        lMensageLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lMensageLogin.setForeground(new java.awt.Color(255, 0, 51));
        lMensageLogin.setText("Login ou Senha Inválida!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lMensageLogin)
                                    .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lMensageLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void loginSuperUser(){
        UsuarioERPBean usuarioERPBean = UsuarioERPBean.getInstance();
        usuarioERPBean.setUsuario(UsuarioERPDAO.ADMIN_USUARIO);
        usuarioERPBean.setSenha(UsuarioERPDAO.ADMIN_SENHA);
        usuarioERPBean.setMestre(true);
        
        PanelPrincipal.getInstance();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UsuarioERPBean usuarioERPBean = UsuarioERPBean.getInstance();
        
        // Se o usuário é o mestre
        if ((tUsuario.getText().toUpperCase().equals(UsuarioERPDAO.ADMIN_USUARIO))
                && (tSenha.getText().equals(UsuarioERPDAO.ADMIN_SENHA))){
            loginSuperUser();
            this.dispose();
        }
        else {
            usuarioERPBean.setUsuario(tUsuario.getText().trim().toUpperCase());        
            usuarioERPBean.setSenha(Criptogafia.Converter(tSenha.getText()));

            try {
                //valida se usuario existe no sistema
                if (this.getUsuarioFacade().validarUsuario(usuarioERPBean)) {
                    //desabilitado até que a ats possa incluir o midler na senha dos clientes
                    // if(validaSenhaCliente())return;
                    PanelPrincipal.getInstance();
                    this.dispose();                
                } else {
                    lMensageLogin.setText("Login ou Senha Inválida");
                    tUsuario.setText("");
                    tSenha.setText("");
                    tUsuario.requestFocus();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar na base de dados.");
                Logger.getLogger(FrameLogin.class).error(ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSenhaKeyPressed
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {            
            if (tSenha.getText().length() > 7){            
                String senha = tSenha.getText();            
                senha = senha.substring(0, 7);
                tSenha.setText(senha);
            }
        }
    }//GEN-LAST:event_tSenhaKeyPressed

    
    /**
     * Valida senha do cliente
     * @return false para senha invalida e true para senha valida
     */
    public boolean validaSenhaCliente(){
       SenhaInstalacaoController senhaController = new SenhaInstalacaoController();
       SenhaSistemaService senhaSistemaService = new SenhaSistemaService();
       try{
          SenhaInstalacaoERPBean senhaInstalacao = senhaController.retornaSenha(); 
          if (senhaInstalacao != null) {
             SenhaSistema senhaSistema = senhaSistemaService.parse(senhaInstalacao.getSenha());
             //verifica se a senha do cliente possui acesso ao midler
             if (!senhaSistema.getSistemas().containsKey("MID")) {
                JOptionPane.showMessageDialog(null, "Esta senha não possui permissão para este sistema!");
                tUsuario.setText("");
                tSenha.setText("");
                tUsuario.requestFocus();
                lMensageLogin.setText("");
                return false;
             }
             Date dataAtual = new Date();
             //se a data de validade da senha esta expirada
             if (dataAtual.after(senhaSistema.getDataValidade())) {
                JOptionPane.showMessageDialog(null, "Senha com data de vencimento expirada!");
                tUsuario.setText("");
                tSenha.setText("");
                tUsuario.requestFocus();
                lMensageLogin.setText("");
                return false;
             }
          }
          Logger.getLogger(FrameLogin.class).info("Senha validada com sucesso!");
          return true;
       }catch(Exception e){
          Logger.getLogger(FrameLogin.class).info("Erro ao validar senha: "+e); 
          return false;
           
       }
       
    }

    public UsuarioERPFacade getUsuarioFacade() {
        if (this.usuarioFacade == null) {
            this.usuarioFacade = new UsuarioERPFacade();
        }
        return usuarioFacade;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lMensageLogin;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
