/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atsinformatica.midler.ui;

import br.com.atsinformatica.erp.controller.LogEcomErroController;
import br.com.atsinformatica.erp.entity.LogErroEcomBean;
import br.com.atsinformatica.midler.components.renderer.DateTimeCellRenderer;
import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import java.util.List;

/**
 *
 * @author AlexsanderPimenta
 */
public class LogErrosDialog extends javax.swing.JDialog {
    
    private AnnotationResolver resolver = new AnnotationResolver(LogErroEcomBean.class);
    private String fields = "id,idInteg,descricaoErro,dataErro";
    private ObjectTableModel modelLogErro = new ObjectTableModel(resolver, fields);
    private LogEcomErroController logErroController = new LogEcomErroController();
    
    /**
     * Creates new form LogErrosDialog
     */
    public LogErrosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        this.setTitle("Log de erros");
        carregaGrid();      
    }
    
    
    public void refreshData(int id){
        modelLogErro.clear();
        List<LogErroEcomBean> logErros = logErroController.listaLogErros(id);
        modelLogErro.addAll(logErros);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbLogErro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTbLogErro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Id integração", "Descrição erro", "Data erro"
            }
        ));
        jTbLogErro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTbLogErro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        modelLogErro.clear();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogErrosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogErrosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogErrosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogErrosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogErrosDialog dialog = new LogErrosDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbLogErro;
    // End of variables declaration//GEN-END:variables

    private void carregaGrid() {
        jTbLogErro.setModel(modelLogErro);        
        jTbLogErro.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTbLogErro.getColumnModel().getColumn(2).setPreferredWidth(600);
        jTbLogErro.getColumnModel().getColumn(3).setCellRenderer(new DateTimeCellRenderer());
        jTbLogErro.getColumnModel().getColumn(3).setPreferredWidth(158);
        jTbLogErro.getColumnModel().getColumn(0).setPreferredWidth(70);        
        jTbLogErro.getColumnModel().getColumn(1).setMinWidth(90);
        jTbLogErro.getColumnModel().getColumn(2).setMinWidth(600);
        jTbLogErro.getColumnModel().getColumn(3).setMinWidth(158);
        jTbLogErro.getColumnModel().getColumn(0).setMinWidth(70);        
        
    }
}
